### ISSUE TITLE
Color code names based on hours worked

### ISSUE THREAD

**Issue by blevenson** [pjztam/TimecardsForever#1]
If someone is not close to meeting their hours, color code their name red.  If they are on track, color code their name yellow.  And if they have met or surpassed the requirement, color code it green.  A fun feature would have it determine how many hours you need each day and if you are not close then it marks you red.

**Comment by pjztam** [comment]
What are the requirements?

**Comment by blevenson** [comment]
I don't know yet. Set them to 100 for now and when the leaders(parents, so the number might fall to about 2 or 3. Lol classic parents. ) decide you can just change it easily. Or wait. Whatever floats your metiforical boat.

**Comment by blevenson** [comment]
42 is the requirement...but round up to 50.

**Comment by pjztam** [comment]
I've added little checkmarks to the admin list page to denote who is over their needed hours. Color coding looked ugly so I didn't go through with it.
