### ISSUE TITLE
Implement easy add/ remove

### ISSUE THREAD

**Issue by blevenson** [pjztam/TimecardsForever#3]
Implement a simple way for admins to add / remove hours in case any problems occur. By doing this admins will gain a lot more power which means there should be a sperate accout to log people in and out that doesn't have admin power(see other issue)

**Comment by pjztam** [comment]
adding hours will probably not happen because of the way the system is designed. it assumes that all clock ins are in chronological order, and adding hours here and there would screw that up. removing hours will probably happen.
